server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bakery?ServerTimezone=Asia/Seoul&useUnicode=true&characterEncdoing=utf8mb4
    username: root
    password: xogns4586-

  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      format_sql: true
      show-sql : true
      use_sql_comments: true


logging:
  level:
    org:
      type:
        descriptor:
          sql: true
      SQL: true
